// <auto-generated />
using System;
using ByTech_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ByTech_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417173014_categoria")]
    partial class categoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ByTech_API.Models.CampanhaEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("id_admin");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("assunto");

                    b.Property<string>("CorpoMensagem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("corpo_mensagem");

                    b.Property<DateTime>("Data_Disparo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_disparo");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("campanha_email", (string)null);
                });

            modelBuilder.Entity("ByTech_API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("ByTech_API.Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("PrecoUnitarioPago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_unitario_pago");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("id_produto");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INT(11)")
                        .HasColumnName("quantidade");

                    b.Property<int>("VendaId")
                        .HasColumnType("int")
                        .HasColumnName("id_venda");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("item_venda", (string)null);
                });

            modelBuilder.Entity("ByTech_API.Models.MensagensContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("celular");

                    b.Property<DateTime>("Data_Envio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_envio");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_visitante");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("mensagem_contato", (string)null);
                });

            modelBuilder.Entity("ByTech_API.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataConfirmacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_confirmacao");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("metodo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("VendaId")
                        .HasColumnType("int")
                        .HasColumnName("id_venda");

                    b.HasKey("Id");

                    b.HasIndex("VendaId")
                        .IsUnique();

                    b.ToTable("pagamento", (string)null);
                });

            modelBuilder.Entity("ByTech_API.Models.PedidoVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_pedido");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("ValorTotalPedido")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_total_pedido");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("pedido_venda", (string)null);
                });

            modelBuilder.Entity("ByTech_API.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<int>("EstoqueAtual")
                        .HasColumnType("int")
                        .HasColumnName("estoque_atual");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("imagem");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("marca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_venda");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("ByTech_API.Models.ServicoManutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<DateTime>("Data_Entrada")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_entrada");

                    b.Property<string>("Descricao_Problema")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao_problema");

                    b.Property<string>("Equipamento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("equipamento");

                    b.Property<string>("Observacoes_Tecnicas")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("observacoes_tecnicas");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("protocolo");

                    b.Property<string>("Status_Servico")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status_servico");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int")
                        .HasColumnName("id_tecnico");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("servico_manutencao", (string)null);
                });

            modelBuilder.Entity("ByTech_API.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("senha");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("ByTech_API.Models.CampanhaEmail", b =>
                {
                    b.HasOne("ByTech_API.Models.Usuarios", "UsuarioAdmin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioAdmin");
                });

            modelBuilder.Entity("ByTech_API.Models.ItemVenda", b =>
                {
                    b.HasOne("ByTech_API.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByTech_API.Models.PedidoVenda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ByTech_API.Models.MensagensContato", b =>
                {
                    b.HasOne("ByTech_API.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ByTech_API.Models.Pagamento", b =>
                {
                    b.HasOne("ByTech_API.Models.PedidoVenda", "Venda")
                        .WithOne()
                        .HasForeignKey("ByTech_API.Models.Pagamento", "VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ByTech_API.Models.PedidoVenda", b =>
                {
                    b.HasOne("ByTech_API.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ByTech_API.Models.Produto", b =>
                {
                    b.HasOne("ByTech_API.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ByTech_API.Models.ServicoManutencao", b =>
                {
                    b.HasOne("ByTech_API.Models.Usuarios", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByTech_API.Models.Usuarios", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Tecnico");
                });
#pragma warning restore 612, 618
        }
    }
}
